# Site settings
title: "The Magic of Sage"
tagline: The magic of sage! # it will display as the sub-title
description: 

author: Atit Vakharia
email: atit.vakharia@gmail.com
twitter_username: avakharia
github_username: avakharia

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# The language of the webpage › http://www.lingoes.net/en/translator/langcode.htm
# If it has the same name as one of the files in folder `_data/locales`, the layout language will also be changed,
# otherwise, the layout language will use the default value of 'en'.
lang: en

# Change to your timezone › http://www.timezoneconverter.com/cgi-bin/findzone/findzone
timezone: America/Chicago

google_analytics_id: G-LDWGSSKWHE
disqus_id:

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title.html

sass:
    style: compressed

exclude: [vendor]

