# Site settings
title: Sagical
tagline: Sagical # it will display as the sub-title
description: "Hi, I’m Atit and I live in the Sports City. I’m a son, a brother, a husband and most importantly a father of two beautiful kiddos. I recently started writing about my leadership experiences with the hope to share not only my perspective but also to encourage a dialogue. I can’t wait to learn from the community along this journey."

author: Atit Vakharia
email: atit.vakharia@gmail.com
twitter_username: avakharia
github_username: 
linkedin_username: avakharia

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://avakharia.github.io/" # the base hostname & protocol for your site

# The language of the webpage › http://www.lingoes.net/en/translator/langcode.htm
# If it has the same name as one of the files in folder `_data/locales`, the layout language will also be changed,
# otherwise, the layout language will use the default value of 'en'.
lang: en

# Change to your timezone › http://www.timezoneconverter.com/cgi-bin/findzone/findzone
timezone: America/Chicago

google_analytics_id: G-LDWGSSKWHE
disqus_id: avbitstipsblog

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title.html

sass:
    style: compressed

exclude: [vendor]

